kubewarden/policy-fetcher

src/lib.rs
Fixes: https://github.com/kubewarden/policy-fetcher/issues/9
=> feat: if a policy tag on a registry is latest, pull always

src/lib.rs
When the user doesn't specify a url scheme, use the `registry://` one.
This makes possible to copy and paste policy urls from hub.kubewarden.io into `kwctl pull`
This provides a smoother UX
=> Pull from registry by default

src/lib.rs
This struct contains information about the remote URL, as well as the
local URL where the policy was fetched to
=> API: fetch returns a Policy structure

src/verify.rs
The verification of the signed manifest digest and the digest of the local `.wasm` file cannot be done using the Policy URL (e.g.: `registry://ghcr.io/kubewarden/foo:latest`).
While `kwctl` downloads all the policies into the central store (making possible to find the path to the wasm file, starting from the URI), the Policy Server can download policies into arbitrary locations.
The API of the verifier has been changed to take a `Policy` object, instead of a `str` containing the URI.
The Policy object has already two attributes: the URI and the path to the `.wasm` file.
This change is required to implement Sigstore verification inside of Policy Server.
=> Change verifier API

src/registry/config.rs
Related: https://github.com/kubewarden/kwctl/issues/105
When this configuration file exists, it doesn't mean that it must
contain a toplevel `auths` key and we have found instances where this
was not the case. Therefore, make this toplevel key optional.
=> chore: make ~/.docker/config.json auths toplevel key optional

Cargo.toml, src/lib.rs
This release introduces the new functions required to interact with sigstore.
=> Tag 0.5.0 release

Cargo.toml
=> bump version to 0.6.1

Cargo.toml, src/verify/mod.rs
=> Change error message when sigstore signatures are not found

src/lib.rs, src/sources.rs, src/store.rs, src/verify/config.rs
Fixes the issues found by the latest clippy version used in the stable rustup toolchain.
=> Clippy issues fixes.

src/lib.rs
Prior to this commit, a policy url like `ghcr.io:443/kubewarde/policy1:latest` would cause the url scheme to be `ghcr.io`.
This commit urls with port numbers are always handled correctly.
Fixes https://github.com/kubewarden/policy-fetcher/issues/131
=> fix: correct parsing of some policy urls

src/lib.rs, src/registry/mod.rs
Provide more context when an image cannot be pulled.
=> fix: improve error handling

Cargo.toml
Update Cargo.toml with the new version
=> chore: prepare for v0.8.0 release

src/lib.rs
Resolves: https://github.com/kubewarden/kwctl/issues/554
Adds `:latest` to the destination filename if no tag is present.
Will test in kwctl e2e tests
-
=> fix: add latest tag when no tag is present

.github/workflows/tests.yml
Express GH actions deps using full version
=> chore(deps): be explicit about GH dependencies

.github/workflows/tests.yml, .gitignore, Makefile, coverage/integration-tests/.gitignore, coverage/unit-tests/.gitignore
Fix https://github.com/kubewarden/kubewarden-controller/issues/641
CI, codecov message.
=> ci: Add codecov support

src/verify/mod.rs
Needed by: https://github.com/kubewarden/policy-evaluator/pull/455
=> fix: add derive clone to verifier

Cargo.toml
=> chore: bump version to v0.8.3

Cargo.toml
=> build(deps): remove unused dependencies

Cargo.toml, src/sources.rs, src/verify/config.rs, src/verify/verification_constraints.rs
**UPDATED:** Ensures policy-fetcher works fine the latest stable version of Sigstore
=> chore(deps): update to latest version of Sigstore

.github/workflows/tests.yml, .typos.toml, Makefile, src/sources.rs, src/store/errors.rs, src/verify/errors.rs, src/verify/mod.rs, tests/sources.rs
Use `crate-ci/typos` to detect typos.
=> test: verify typos

.github/workflows/tests.yml, .github/workflows/update-rust-toolchain.yaml, rust-toolchain.toml, updatecli/DEVELOP.md, updatecli/updatecli.d/update-rust-toolchain.yaml, updatecli/values.yaml
Adds the rust-toolchain.toml file to configure the build command on witch toolchain and target it should use.
Related to https://github.com/kubewarden/kubewarden-controller/issues/1093
=> chore(deps): add rust-toolchain.toml.

Cargo.toml
Update sigstore-rs and other dependencies to latest version.
=> chore(deps): update dependencies
