kubewarden/policy-fetcher

Cargo.lock
Cargo.toml
src/registry/mod.rs

This PR fixes the push operations against ghcr and against generic registries secured by TLS.
The oci-distribution crate was affected by a bug that caused pushes against ghcr.io (and probably other registries) to fail. Our code now builds against a fork of oci-distribution. This will be changed once upstream publishes a new version of the crate that includes this fix.
Finally, prior to this commit, the `push` code was nevertheless broken when dealing with registries secured by TLS. The code would push over TLS and then, even when the push completed successfully, would perform another push over plain HTTP. The second push is not needed, plus it always leads to a failure (pushing over plain HTTP against a HTTPS endpoint).
Once this PR is merged I'll tag a new release of policy-fetcher

Fix ghcr push

---

src/registry/config.rs
tests/common.rs
tests/parse_docker_config_json.rs
tests/test_data/auth-present.json
tests/test_data/auth-some-missing.json

Fixes: https://github.com/kubewarden/kwctl/issues/47
`kubectl` has generated docker config json files that miss the `auth`
key in the `auths` field [1].
Due to this, make the parsing of the dockerconfigjson file less
strict, with an optional `auth` field. If this field is not present,
the host will be ignored, but the rest of the file will apply.
We keep the same behavior of a complete failure in the following
cases:
- The JSON file is not syntactically valid
- The basic auth information is not valid base64
- The decoded base64 is not in the form `username:password`.
[1] https://github.com/kubernetes/kubectl/issues/571

feat: ignore invalid host configuration on the dockerconfigjson

---

src/lib.rs
src/registry/mod.rs

If port is present, check `host+port` in the insecure hosts mapping to
determine if we should retry the pull/push.

Check host+port when checking for insecure hosts

---

src/verify.rs

Add `verifier::verify_local_file_checksum()`. As input, it uses a verified manifest digest. That way the callers are
aware that this function should only be called on verified policies.
Refactor with breaking change: Return verified manifest digest in `verifier::verify()`, and don't silently compare checksums there.
Needed by https://github.com/kubewarden/kwctl/pull/84.

feat!: Add `verifier::verify_local_file_checksum()`, return manifests on `verifier::verify()`

---

Cargo.toml
src/lib.rs
src/registry/mod.rs
src/verify.rs

Expose a method to fetch the manifest digest. This is needed so that we can expose this function to our policies.
While at that, I also did some refactoring of function params: from `&Option<T>` to `Option<&T>`.

expose fetch manifest digest

---

Cargo.toml
src/fetcher.rs
src/lib.rs
src/registry/mod.rs

Some of the methods of the `Registry` struct are going to be used against container images, not kubewarden policies.
For example, this will happen to the methods dealing with OCI objects manifests (regardless of them being images or artifacts).
A policy might rely on this method to obtain the digest of a container image that is mentioned inside of a Pod `spec` section.
We have no control over these container images, they could also be images coming from the Docker Hub or even from the "Docker Hub library".
That means that we must be able to handle OCI object names like `busybox`, `opensuse/leap`.
This commits makes `policy-fetcher` rely on a forked version of `oci-distribution`.
This is needed because some important fixes related with image parsing have not yet been released.
Some parts …

Handle operations against Docker Hub

---

src/verify.rs

If no matching signatures with given constraints are found, the vector
being inspected can be empty. In that case, return an error directly.

fix: allow no matching signatures with given constraints

---

Cargo.toml
src/verify.rs

Use the latest releases of these crates.
Bump policy-fetcher to v0.3.1

Update oci-distribution and sigstore-rs deps

---

Cargo.toml
src/registry/mod.rs

Change the API of `Registry::push` to return a value inside of its `Result` response.
The method now returns the immutable reference of the policy that has been pushed.
This information is important, because it allows kwctl users to use cosign (from Sigstore) to sign the **actual** policy that has just been pushed to the repo.
Signing policies by tag is not secure, there could be race conditions or attacks that could lead the user to sign a different content. Signing by immutable ref is not affected by these issues.
Because of this API change, the version of this crate will deserve a minor version bump: `0.3.x` -> `0.4.0`

push return immutable ref

---

Cargo.toml
src/registry/mod.rs
src/store.rs
tests/parse_docker_config_json.rs
tests/test_data/auths-not-present.json

Fixes: https://github.com/kubewarden/kwctl/issues/105
Fixes: https://github.com/kubewarden/kwctl/issues/109
Fix policy store path handling in Windows:
- Replace colons (illegal character name for paths) with a fake colon. This allows us to not do anything special for Windows in terms of policy store structure.
- Always use forward slashes for URL's

Windows path fixes

---

Cargo.toml
src/registry/mod.rs
src/sources.rs
src/verify/config.rs
src/verify/mod.rs
src/verify/verification_constraints.rs

Relates to https://github.com/kubewarden/policy-server/issues/142.
Depends on https://github.com/sigstore/sigstore-rs/pull/40.
Added tests as part of unit tests, run with `make test`.
Refactored the verification algorithm, which filters with contraints, into its own function.
Another option could have been to add integration tests under `tests/`. But that entails mocking the registry and image, with its layers, and the codepath under test wouldn't have grown much, as sigstore-rs has its own tests.

Add verification algorithm tests, and fix failures

---

src/verify/config.rs
src/verify/mod.rs

Introduce a series of types that allow a better versioning of the verification config.
This fixes issue #59

Implement better versioning of VerificationConfig

---

Cargo.toml
src/lib.rs
src/verify/mod.rs

Allow consumers of the library to either provide fulcio and rekor data manually, or by fetching it from a TUF repository.
The crate is now re-exposing the `sigstore` and the `oci-distribution` crates. This is required to simplify dependency management, because these are 2 crates that can be used by consumers of this library.

verifier: improve how fulcio and rekor data is found

---

Cargo.toml
src/lib.rs
src/verify/mod.rs

Small changes to the verification API to use more references to objects. 
These changes are needed to make the policy-server code better (avoid lots of `clone()` invocations).
I've already tested these changes with kwctl, policy-server, policy-evaluator. Everything works fine, I'm pretty sure I'll not need more changes :sweat_smile: 
There's just one last question: we will have to tag a new release. Given these are breaking API changes, should we make it `v0.6.0` or should we go with
`v0.5.1`? I'm bringing up the possibility to have a patch release because `v0.5.0` was tagged just some hours ago...

Changes to the verification API

---

src/verify/mod.rs

Example:
```console
$ kwctl -v verify registry://ghcr.io/kubewarden/policies/pod-privileged:v0.1.10
(...)
2022-03-16T11:15:53.110176Z DEBUG policy_fetcher::verify: Constraint satisfied:
---
kind: githubAction
owner: kubewarden
repo: ~
annotations: ~
2022-03-16T11:15:53.110271Z DEBUG policy_fetcher::verify: Policy successfully verified policy="registry://ghcr.io/kubewarden/policies/pod-privileged:v0.1.10"
2022-03-16T11:15:53.110362Z  INFO kwctl::verify: Policy successfully verified
2022-03-16T11:15:53.110761Z DEBUG Connection{peer=Client}: h2::codec::framed_write: send frame=GoAway { error_code: NO_ERROR, last_stream_id: StreamId(0) }
2022-03-16T11:15:53.111023Z DEBUG Connection{peer=Client}: h2::proto::connection: Connection::poll; connection error error=GoAway(b"", NO_ERROR, Library) …
```

feat: Print debug messages for satisfied constraints

---

Cargo.toml
src/verify/mod.rs

Updates the function used to verify if the signatures are respected to check multiple signatures in parallel. For this, it's used the stream module from async_std crate.
Fix #65

Parallelization of the signatures verifications  . 

---

Cargo.toml
src/lib.rs
src/store.rs
src/verify/mod.rs
tests/common/mod.rs

Fix https://github.com/kubewarden/policy-server/issues/99
Supersedes https://github.com/kubewarden/policy-fetcher/pull/77
- Add pub functions `verify_pub_keys()`, `verify_keyless_exact_match()`. These are shims that translate to an interim `VerificationConfig` and call `verify()`, so only 1 codepath exists, no need for tests.
- re-export kubewarden_policy_sdk through policy-fetcher for consumption.
- Minor refactors and error checking.
I suggest "files-changed" review, given the hard refactors.
TODO: depends on rust sdk work.

feat: Add pub `verify_pub_keys()`, `verify_keyless_exact_match()`

---

Cargo.toml
src/lib.rs

The Rust SDK dependency is no longer needed, we should get rid of it.
This was a leftover from one of the previous iterations of the Sigstore integration.

Remove the dependency on policy-fetcher SDK

---

Cargo.toml
src/verify/mod.rs

Show a more descriptive error when an image does not have signatures. This is the error a user see when an image is not signed:
```
Cannot pull manifest of ghcr.io/kubewarden/test-verify-image-signatures:sha256-706446e9c6667c0880d5da3f39c09a6c7d2114f5a5d6b74a2fafd24ae30d2078.sig: OCI API error: manifest unknown on https://ghcr.io/v2/kubewarden/test-verify-image-signatures/manifests/sha256-706446e9c6667c0880d5da3f39c09a6c7d2114f5a5d6b74a2fafd24ae30d2078.sig
```
With this improvement, the user will see:
```
signatures can't be fetched for image: ghcr.io/kubewarden/test-verify-image-signatures:unsigned
```
Fix #82

feat: add more descriptive error when an image does not have signatures

---

Cargo.toml
src/verify/mod.rs
src/verify/verification_constraints.rs

On GithubVerifier, validate using the `github_workflow_repository`
extension in signature certificate, instead of the `subject`.
The `github_workflow_repository` extension contains the repo of the GH
Action workflow that was triggered, not the one that was called. For
example in the case of consuming a reusable workflow
`octocat/reusable-workflows-repo` in `octocat/example`,
`github_workflow_repository` contains `octocat/example`.
This protects against incorrectly validating signatures that have been
performed in reusable workflows.
Passing unit tests, also tested locally with a policy-server consuming this, and public policies.

GitHub actions extensions

---

Cargo.toml

Use latest sigstore-rs to fix https://github.com/kubewarden/verify-image-signatures/issues/20

bump sigstore-rs to v0.3.2

---

Cargo.toml

This speeds up the build because the git repository doesn't have to be cloned/updated locally.

Consume sigstorers from crates.io

---

Cargo.toml
src/store.rs

Fix the compilation error introduced by the API changes.
Supersedes https://github.com/kubewarden/policy-fetcher/pull/102

Update to latest release of slash-path crate

---

Cargo.toml
src/verify/mod.rs

Do not fail when Fulcio and Rekor data are None. The Sigstore integration will still work, but it will provide some false negatives.
False netative means: a perfectly valid signature produced with keyless mode will be reported as non valid.
This is currently required to handle the case when the upstream TUF repository of Sigstore is broken.

Allow fulcio and rekor data to be None

---

Cargo.toml
src/verify/mod.rs

Upgrade to latest stable release of serde_yaml. This version minor bump breaks the output produced when serializing an object to YAML. Because of that, some unit tests had to be fixed.
If that happens again, we will revisit how the unit tests works to make them more robust.

Upgrade to latest serde_yaml

---

Cargo.toml
src/registry/mod.rs

don't show a warning message if no credentials were provided as this will be the case if a user is pulling from a public registry

No docker credential change loglevel to debug

---

Cargo.toml
src/verify/config.rs
src/verify/mod.rs
src/verify/verification_constraints.rs

Upgrade to latest release of sigstore-rs. This is required to fix https://github.com/kubewarden/verify-image-signatures/issues/20

update to latest sigstore

---

Cargo.toml
src/store.rs

We need to know the path of a policy without the store prefix for saving policies in a tarball.
This PR adds a new method for this

Add policy_path method

---

Cargo.toml
src/store.rs

Windows release is [failing](https://github.com/kubewarden/kwctl/actions/runs/3463242415/jobs/5783488270) because of the following error:
```
116 |         filename
|         ^^^^^^^^
|         expected `&str`, found struct `std::string::String`
|         help: consider borrowing here: `&filename`
```
This PR returns a `String` in `policy_file_name` method to fix this error

Windows fix

---

Cargo.toml
src/verify/mod.rs
src/verify/verification_constraints.rs

Policy evaluator implements all the sigstore verification code by leveraging the Verifier defined inside of this crate.
That's because the types of verification constraints exposed to our policy authors match exactly with what the verifier is capable of.
However, now we need to offer to our policy authors the ability to verify a signature produced by a certificate. This is something that is not relevant for the Verifier (which sole purpose is to verify the policies being pulled by kwcl and policy-server).
Because of that, some internal code of the verifier is now exposed as a reusable public function.
A new constructor has also been created, which allows to reuse a Cosign client. This is needed by policy-evaluator.
This is part of the work needed to address …

refactor: expose reusable code

---

Cargo.toml

Consume the latest stable release of oci-distribution.

deps: update to latest oci-distribution

---

Cargo.toml
src/verify/mod.rs

This is required by the context aware feature.

refactor: allow some structs to be clonable

---

Cargo.toml

Relates to https://github.com/kubewarden/policy-evaluator/pull/294.
Needed to release sigstore with picky bump.
CI

build: Bump version to 0.7.23

---

src/policy.rs
tests/store.rs

Adds Store integration tests, specifically it adds tests for the `list` method.
Tests should pass.
I've used `tempfile` rather than fixtures in the repository since using characters as `:` in the filenames would prevent checking out the repository on Windows machines/
Depends on: #150

test: add store list integration test

---

src/policy.rs
src/store/mod.rs
tests/store.rs

Adds `Store::get_policy_by_uri` and `Store::get_policy_by_sha_prefix`.
The latter takes a partial sha and returns a policy that matches.
Returns error if multiple results are found.
This behavior is similar to the docker cli, see: https://github.com/docker/engine/blob/8955d8da8951695a98eb7e15bead19d402c6eb27/daemon/container.go#L36
Added integration tests.

feat: add Policy getters to Store

---

src/store/mod.rs
tests/store.rs

In the previous implementation, the `read_dir` error was silenced, so when a store with a non-existing root was listed an empty list was returned. See: https://github.com/kubewarden/policy-fetcher/blob/3f73d90678939b7375f5f4cb2ad76ecdec1dfe2f/src/store.rs#L189
Since we now bubble up any error caused by `read_dir`, this was returning an error if the path did not exist breaking the original behavior.
This was breaking e2e tests on kwctl too.
Added an integration test for this scenario.
NOTE: This implementation is probably going to change soon with the Database feature.

fix: list non existing store

---

src/lib.rs
src/sources.rs
src/store/path/windows.rs
tests/sources.rs

As mentioned in this PR comment, we prefer not to use `Result` in tests: 
https://github.com/kubewarden/policy-fetcher/pull/152#discussion_r1311891401
This PR refactors the existing tests that do not comply.
-
Maybe we could create a coding convention and guideline docs for all the rust projects.
This doc could collect testing-related information too: e.g. helper libraries to use, test organization, testing patterns, etc...

chore: do not use Result in tests

---

Cargo.toml

Updates the Cargo.toml file bumping the version to v0.8.2.
Related to https://github.com/kubewarden/policy-evaluator/pull/429#issuecomment-1924541219

chore: bump v0.8.2.

---

src/verify/mod.rs

Updates the function used to verify container image signature to use only the registry name to get the auth data from docker config.json file. The current implementation uses the whole container image URL. Which failed to find the relevant auth data falling back to a anonymous authentication. This is a problem with private registries where access credentials must be used.
To fix this problem, this commit extract the registry name from the container image URL and use it to get the auth data from the config.json file.
Fix #179 
To test this pull request, you can build kwctl using this changes, execute a docker login in the private registry 
1. Generate private/public key pair with cosign
2. Sign docker image
3. Submit signed image to private harbor registry. You can use `demo.goharbor.io` …

fix: do not use image url to get registry auth data.

---

Cargo.toml
src/sources.rs
src/verify/mod.rs

The Sigstore project changed the internals of its TUF repository, which broke sigstore-rs.
This commit update to the latest version of sigstore-rs. The code changes have been caused by the massive changes done by sigstore-rs.
Required to fix https://github.com/kubewarden/kwctl/issues/753

fix: address changes done to Sigstore TUF repository

---

.github/workflows/tests.yml

Enable long paths on windows, otherwise git checkout of tough will fail.
Once merged, I'll tag a new release and propagate that to policy-evaluator. Otherwise kwctl will not build on windows

test: fix build on windows

---

Cargo.toml

We don't want to fall back to use native tls (openssl), that would made impossible to build with muslc
This is required to fix building of policy-server and kwctl

dep: ensure rustls is used

---

src/registry/errors.rs
src/registry/mod.rs
tests/e2e.rs

Updates the registry client adding a method to fetch the container image manifest, its digest and configuration.
Fix https://github.com/kubewarden/policy-evaluator/issues/518
To test this pull request, you can run the following commands:
```shell
make test
```

feat: method to get manifest and config of an OCI image.

---

Cargo.toml

Bumps the version to v0.8.6 to release new method added to get the OCI image manifest and config from the registry.
Related to https://github.com/kubewarden/policy-evaluator/issues/518

chore: bump version to v0.8.6.

---

Cargo.toml

This reverts commit 53518be2244d3daeee66357eb48ab6aace06e614, reversing changes made to d46093f5a5aa52500ba4e31352f6c44a88e8b94f. This is necessary because the v0.8.6 is already accidentally released in a commit out of tree.
Furthermore, it bumps the version to v0.8.7 to release new method added to get the OCI image manifest and config from the registry.
Related to https://github.com/kubewarden/policy-evaluator/issues/518

Bumps v0.8.7

---

tests/e2e.rs

Disable the tests to validate the registry authentication on Windows. The test uses the registry container image which is not supported on Windows.
Fix #193

fix(tests): disables auth registry tests on windows.

---

src/lib.rs

Under special circumstances, some code that makes uses of policy-fetcher does not compile.
That happens when the consumer of policy-fetcher is created inside of a tokio task with `tokio::spawn()`.
That happens because the private `url_fetcher` takes as a parameter something that implements the `PolicyFetcher` trait, but is not explicit about requiring also the `Send` attribute. The `Send` attribute is required by tokio to move the task between its worker threads.
Once this is merged I'll tag a new patch release of the crate. This is required by the integration tests of `policy-server` to test the certificate reload.

fix: ensure consumers of policy-fetcher can compile

---

Cargo.toml
src/lib.rs
src/registry/errors.rs
src/registry/mod.rs
src/sources.rs
src/verify/errors.rs
src/verify/mod.rs
tests/e2e.rs

The crate is now called `oci-client`.
Once this is merged, I'll tag a new release of policy-fetcher and propagate the change to kwctl, policy-server and policy-evaluator

chore(deps): oci-distribution has been renamed

---

Cargo.toml

Bump the sigstore-rs dependency to fix a breaking change introduced by upstream

Tag 0.8.10

---

src/fetcher.rs
src/registry/mod.rs
src/sources.rs

Add more logging statements when pushing to an insecure registry.
We had a user that was struggling to understand why pushing to a certain registry didn't work despite `insecure` being turned on.
We finally figured out that was happening because of a reverse proxy was misconfigured. However, the error obtained from the insecure proxy was silently swallowed.
Moreover, I fixed some clippy warnings introduced by latest release of Rust

add more logging

---

Cargo.toml

The contents of Sigstore's TUF repository have been recently changed and, due to a mistake, the sigstore-rs was broken.
This commit consumes a forked version of sigstore-rs, which consumes a forked version of the tough crate.
This is required to fix https://github.com/sigstore/sigstore-rs/issues/429 until upstream changes the contents of TUF's repository.

fix: address broken sigstore's TUF repository

---

.taplo.toml
Cargo.toml
src/registry/mod.rs
src/sources.rs
tests/e2e.rs

Prior to this PR, some methods exposed by the `Registry` struct did not handle properly interactions with HTTP registries.
This made impossible to fetch OCI manifests and configurations from certain registries.
This commit fixes the problem and refactors the code to avoid repetitions.
New e2e tests have been added that interact with http and https registries.
Finally, some structs internals have been made public to simplify the process of creating them.
For example, the `Sources` struct could be created only by deserializing the contents of a `sources.yaml` file. This made testing (and library consumpion) really hard.
While working on this PR, I've also added a [taplo](https://taplo.tamasfe.dev/) configuration that can be used to format the `Cargo.toml` file in a consistent way.

fix: http registry interactions

---

src/registry/mod.rs

Use `debug` instead of `warn` level when pushing a policy. This reduces the noise we produce when doing `kwctl push`.

fix: change log level when pushing policy

---

.github/workflows/tests.yml

Removes the deprecated actions-rs/cargo Github action used to run cargo commands.
Related to https://github.com/kubewarden/kubewarden-controller/issues/1092

fix(deps): remove deprecated actions-rs/cargo Github action.
